# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57a9f62ddecd13d9b87c0d0bdc4a0d221e25d775e5bb5db6dd761977f1954ce65fe917736e7ccf2b3268dd89c7772a0c1a85491c1dde148d1d7b0caa73de93ea

test:
  secret_key_base: ab79ea99ac5336c1057f665ca4f6be23e355b48534b0a26bf0919ac5e5b20b57b2fefd315f622f87e1bc8410359df6823fc544c9a57dcd88deb552d5dee176a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
