# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
Student.create!(name: 'Bill Johnson')
Student.create!(name: 'Chris Johnson')
Student.create!(name: 'Bill Williams')
Student.create!(name: 'Tom Jackson')
Student.create!(name: 'Willie Mays')
Student.create!(name: 'Mike Thomas')
Student.create!(name: 'Karen Willis')
Student.create!(name: 'Jen Anderson')
Student.create!(name: 'Lisa Schafer')
Student.create!(name: 'Pete Reed')
Student.create!(name: 'Ty Johnson')
Student.create!(name: 'Ashley Meeks')
Student.create!(name: 'Christian Johnson')
Student.create!(name: 'Ryan Hills')
Student.create!(name: 'Ivy Boss')
Student.create!(name: 'Evan Lewis')
Student.create!(name: 'Nancy Ashlin')

Course.create!(name: "English", period: 1)
Course.create!(name: "Spanish", period: 1)
Course.create!(name: "Russian", period: 1)
Course.create!(name: "Chemistry", period: 2)
Course.create!(name: "Biology", period: 2)
Course.create!(name: "Marketing", period: 3)
Course.create!(name: "Management", period: 3)
Course.create!(name: "Business", period: 3)
Course.create!(name: "Economics", period: 4)
Course.create!(name: "Language Arts", period: 4)
Course.create!(name: "Health", period: 5)
Course.create!(name: "PE", period: 5)
Course.create!(name: "History", period: 6)
Course.create!(name: "Algebra", period: 6)
Course.create!(name: "Computer science", period: 7)
Course.create!(name: "Geometry", period: 7)
Course.create!(name: "Geography", period: 8)
Course.create!(name: "Physics", period: 8)

Enrollment.create!(student_id: 1, course_id: 1)
Enrollment.create!(student_id: 1, course_id: 4)
Enrollment.create!(student_id: 1, course_id: 6)
Enrollment.create!(student_id: 1, course_id: 11)
Enrollment.create!(student_id: 1, course_id: 14)
Enrollment.create!(student_id: 1, course_id: 17)

Enrollment.create!(student_id: 2, course_id: 1)
Enrollment.create!(student_id: 2, course_id: 4)
Enrollment.create!(student_id: 2, course_id: 7)
Enrollment.create!(student_id: 2, course_id: 10)
Enrollment.create!(student_id: 2, course_id: 14)
Enrollment.create!(student_id: 2, course_id: 15)
Enrollment.create!(student_id: 2, course_id: 17)

Enrollment.create!(student_id: 3, course_id: 2)
Enrollment.create!(student_id: 3, course_id: 4)
Enrollment.create!(student_id: 3, course_id: 8)
Enrollment.create!(student_id: 3, course_id: 11)
Enrollment.create!(student_id: 3, course_id: 13)
Enrollment.create!(student_id: 3, course_id: 17)

Enrollment.create!(student_id: 4, course_id: 4)
Enrollment.create!(student_id: 4, course_id: 6)
Enrollment.create!(student_id: 4, course_id: 10)
Enrollment.create!(student_id: 4, course_id: 12)
Enrollment.create!(student_id: 4, course_id: 13)
Enrollment.create!(student_id: 4, course_id: 17)

Enrollment.create!(student_id: 5, course_id: 3)
Enrollment.create!(student_id: 5, course_id: 6)
Enrollment.create!(student_id: 5, course_id: 9)
Enrollment.create!(student_id: 5, course_id: 12)
Enrollment.create!(student_id: 5, course_id: 14)
Enrollment.create!(student_id: 5, course_id: 15)

Enrollment.create!(student_id: 6, course_id: 1)
Enrollment.create!(student_id: 6, course_id: 4)
Enrollment.create!(student_id: 6, course_id: 6)
Enrollment.create!(student_id: 6, course_id: 9)
Enrollment.create!(student_id: 6, course_id: 11)
Enrollment.create!(student_id: 6, course_id: 13)

Enrollment.create!(student_id: 7, course_id: 3)
Enrollment.create!(student_id: 7, course_id: 5)
Enrollment.create!(student_id: 7, course_id: 8)
Enrollment.create!(student_id: 7, course_id: 10)
Enrollment.create!(student_id: 7, course_id: 12)
Enrollment.create!(student_id: 7, course_id: 14)
Enrollment.create!(student_id: 7, course_id: 16)

Enrollment.create!(student_id: 8, course_id: 2)
Enrollment.create!(student_id: 8, course_id: 4)
Enrollment.create!(student_id: 8, course_id: 7)
Enrollment.create!(student_id: 8, course_id: 9)
Enrollment.create!(student_id: 8, course_id: 11)
Enrollment.create!(student_id: 8, course_id: 13)
Enrollment.create!(student_id: 8, course_id: 15)

Enrollment.create!(student_id: 9, course_id: 4)
Enrollment.create!(student_id: 9, course_id: 8)
Enrollment.create!(student_id: 9, course_id: 10)
Enrollment.create!(student_id: 9, course_id: 11)
Enrollment.create!(student_id: 9, course_id: 14)
Enrollment.create!(student_id: 9, course_id: 17)

Enrollment.create!(student_id: 10, course_id: 1)
Enrollment.create!(student_id: 10, course_id: 4)
Enrollment.create!(student_id: 10, course_id: 6)
Enrollment.create!(student_id: 10, course_id: 11)
Enrollment.create!(student_id: 10, course_id: 13)
Enrollment.create!(student_id: 10, course_id: 15)
Enrollment.create!(student_id: 10, course_id: 17)

Enrollment.create!(student_id: 11, course_id: 6)
Enrollment.create!(student_id: 11, course_id: 9)
Enrollment.create!(student_id: 11, course_id: 11)
Enrollment.create!(student_id: 11, course_id: 13)
Enrollment.create!(student_id: 11, course_id: 15)
Enrollment.create!(student_id: 11, course_id: 17)

Enrollment.create!(student_id: 12, course_id: 1)
Enrollment.create!(student_id: 12, course_id: 4)
Enrollment.create!(student_id: 12, course_id: 6)
Enrollment.create!(student_id: 12, course_id: 9)
Enrollment.create!(student_id: 12, course_id: 11)
Enrollment.create!(student_id: 12, course_id: 15)
Enrollment.create!(student_id: 12, course_id: 17)

Enrollment.create!(student_id: 13, course_id: 2)
Enrollment.create!(student_id: 13, course_id: 5)
Enrollment.create!(student_id: 13, course_id: 6)
Enrollment.create!(student_id: 13, course_id: 11)
Enrollment.create!(student_id: 13, course_id: 13)
Enrollment.create!(student_id: 13, course_id: 15)
Enrollment.create!(student_id: 13, course_id: 17)

Enrollment.create!(student_id: 14, course_id: 3)
Enrollment.create!(student_id: 14, course_id: 4)
Enrollment.create!(student_id: 14, course_id: 6)
Enrollment.create!(student_id: 14, course_id: 9)
Enrollment.create!(student_id: 14, course_id: 13)
Enrollment.create!(student_id: 14, course_id: 15)

Enrollment.create!(student_id: 15, course_id: 6)
Enrollment.create!(student_id: 15, course_id: 9)
Enrollment.create!(student_id: 15, course_id: 11)
Enrollment.create!(student_id: 15, course_id: 13)
Enrollment.create!(student_id: 15, course_id: 15)
Enrollment.create!(student_id: 15, course_id: 17)

Enrollment.create!(student_id: 16, course_id: 3)
Enrollment.create!(student_id: 16, course_id: 5)
Enrollment.create!(student_id: 16, course_id: 8)
Enrollment.create!(student_id: 16, course_id: 10)
Enrollment.create!(student_id: 16, course_id: 12)
Enrollment.create!(student_id: 16, course_id: 14)
Enrollment.create!(student_id: 16, course_id: 16)

Enrollment.create!(student_id: 17, course_id: 2)
Enrollment.create!(student_id: 17, course_id: 5)
Enrollment.create!(student_id: 17, course_id: 7)
Enrollment.create!(student_id: 17, course_id: 10)
Enrollment.create!(student_id: 17, course_id: 12)
Enrollment.create!(student_id: 17, course_id: 14)
Enrollment.create!(student_id: 17, course_id: 17)
